import type { PatientCase, DistressHistoryEntry, InterventionRecommendation, PatientCheckInPayload } from '../types';
import { MOCK_PATIENT_CASES } from '../data/mockCases';
import { getInterventionsForRisk } from '../data/interventions';

// Simulated artificial network latency helper (400ms)
const delay = (ms: number = 400) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * BACKEND INTEGRATION POINT: GET /api/cases?state=&district=
 * In production, server-side jurisdiction filtering must happen on the backend database queries.
 * Frontend passes JWT token in Authorization header, and backend verifies counsellor's state & district claims.
 */
export const fetchCasesByJurisdiction = async (state: string, district: string): Promise<PatientCase[]> => {
  await delay(350);
  
  // Filter cases strictly matching counsellor's assigned State & District
  const filtered = MOCK_PATIENT_CASES.filter(
    (c) => c.state.toLowerCase() === state.toLowerCase() && c.district.toLowerCase() === district.toLowerCase()
  );

  // Sort by risk level: RED -> AMBER -> GREEN
  const riskPriority = { RED: 0, AMBER: 1, GREEN: 2 };
  return filtered.sort((a, b) => riskPriority[a.riskLevel] - riskPriority[b.riskLevel]);
};

/**
 * BACKEND INTEGRATION POINT: GET /api/cases/:id/distress-history
 * Retrieves full multi-week distress trajectory and predicted future scores generated by AI forecasting model.
 */
export const fetchCaseDistressHistory = async (caseId: string): Promise<DistressHistoryEntry[]> => {
  await delay(250);
  const found = MOCK_PATIENT_CASES.find((c) => c.id === caseId);
  return found ? found.distressHistory : [];
};

/**
 * BACKEND INTEGRATION POINT: GET /api/cases/:id/recommendations
 * Fetches AI-generated intervention recommendations customized for the patient's current risk level.
 */
export const fetchCaseRecommendations = async (riskLevel: 'GREEN' | 'AMBER' | 'RED'): Promise<InterventionRecommendation[]> => {
  await delay(300);
  return getInterventionsForRisk(riskLevel);
};

/**
 * BACKEND INTEGRATION POINT: POST /api/patient/checkin
 * Processes daily patient check-in with mood score, text NLP analysis, and voice sentiment scoring.
 */
export const submitPatientCheckIn = async (payload: PatientCheckInPayload): Promise<{ success: boolean; checkInId: string; message: string }> => {
  await delay(600);
  console.log('[API POST /api/patient/checkin] Received payload:', payload);
  return {
    success: true,
    checkInId: `CHK-${Math.floor(100000 + Math.random() * 900000)}`,
    message: "Check-in logged securely. Your state mental health response team is active."
  };
};
