import type { PatientCase, DistressHistoryEntry, InterventionRecommendation, PatientCheckInPayload } from '../types';
import { MOCK_PATIENT_CASES } from '../data/mockCases';
import { getInterventionsForRisk } from '../data/interventions';

// Simulated artificial network latency helper (400ms)
const delay = (ms: number = 400) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * BACKEND INTEGRATION POINT: GET /api/cases?state=&district=
 * In production, server-side jurisdiction filtering must happen on the backend database queries.
 * Frontend passes JWT token in Authorization header, and backend verifies counsellor's state & district claims.
 */
export const fetchCasesByJurisdiction = async (state: string, district: string): Promise<PatientCase[]> => {
  await delay(350);
  
  // Filter cases strictly matching counsellor's assigned State & District
  const filtered = MOCK_PATIENT_CASES.filter(
    (c) => c.state.toLowerCase() === state.toLowerCase() && c.district.toLowerCase() === district.toLowerCase()
  );

  // Sort by risk level: RED -> YELLOW -> GREEN
  const riskPriority = { RED: 0, YELLOW: 1, GREEN: 2 };
  
  return filtered.sort((a, b) => {
    // Primary sort: Risk Level
    if (riskPriority[a.riskLevel] !== riskPriority[b.riskLevel]) {
      return riskPriority[a.riskLevel] - riskPriority[b.riskLevel];
    }
    // Secondary sort: Distress Score
    return b.currentScore - a.currentScore;
  });
};

/**
 * BACKEND INTEGRATION POINT: GET /api/cases/:id/distress-history
 * Retrieves full multi-week distress trajectory and predicted future scores generated by AI forecasting model.
 */
export const fetchCaseDistressHistory = async (caseId: string): Promise<DistressHistoryEntry[]> => {
  await delay(250);
  const found = MOCK_PATIENT_CASES.find((c) => c.id === caseId);
  return found ? found.distressHistory : [];
};

/**
 * BACKEND INTEGRATION POINT: GET /api/cases/:id/recommendations
 * Fetches AI-generated intervention recommendations customized for the patient's current risk level.
 */
export const fetchCaseRecommendations = async (riskLevel: 'GREEN' | 'YELLOW' | 'RED'): Promise<InterventionRecommendation[]> => {
  await delay(300);
  return getInterventionsForRisk(riskLevel);
};

/**
 * BACKEND INTEGRATION POINT: POST /api/patient/checkin
 * Processes daily patient check-in with mood score, text NLP analysis, and voice sentiment scoring.
 */
export const submitPatientCheckIn = async (payload: PatientCheckInPayload): Promise<{ success: boolean; checkInId: string; message: string }> => {
  await delay(600);
  console.log('[API POST /api/patient/checkin] Received payload:', payload);
  return {
    success: true,
    checkInId: `CHK-${Math.floor(100000 + Math.random() * 900000)}`,
    message: "Check-in logged securely. Your state mental health response team is active."
  };
};

/**
 * BACKEND INTEGRATION POINT: GET /api/messages?caseId= / WebSocket /ws/chat
 * Retrieves full conversation history between assigned counsellor and patient case.
 */
export const fetchChatMessages = async (caseId: string) => {
  await delay(200);
  const saved = localStorage.getItem('sahay_chats');
  const chats = saved ? JSON.parse(saved) : {};
  return chats[caseId] || [];
};

/**
 * BACKEND INTEGRATION POINT: POST /api/messages (text/voice)
 * Sends text or voice message to patient thread and broadcasts via WebSocket.
 */
export const sendChatMessageApi = async (messageData: any) => {
  await delay(300);
  console.log('[API POST /api/messages]', messageData);
  return { success: true, messageId: `msg-${Date.now()}` };
};

/**
 * BACKEND INTEGRATION POINT: GET /api/meetings?counsellorId=
 * Fetches scheduled tele-consultation meetings for counsellor's assigned cases.
 */
export const fetchCounsellorMeetingsApi = async () => {
  await delay(250);
  const saved = localStorage.getItem('sahay_meetings');
  return saved ? JSON.parse(saved) : [];
};

/**
 * BACKEND INTEGRATION POINT: POST /api/sos/:caseId/resolve
 * Resolves active SOS emergency alert with mandatory dispatch/notes confirmation.
 */
export const resolveSosAlertApi = async (sosId: string, action: string, notes: string) => {
  await delay(400);
  console.log('[API POST /api/sos/:caseId/resolve]', { sosId, action, notes });
  return { success: true, timestamp: new Date().toISOString() };
};

/**
 * BACKEND INTEGRATION POINT: GET /api/reports?caseId=
 * Retrieves shared mental health trajectory reports submitted by patients.
 */
export const fetchSharedReportsApi = async (caseId: string) => {
  await delay(250);
  const saved = localStorage.getItem('sahay_shared_reports');
  const reports = saved ? JSON.parse(saved) : [];
  return reports.filter((r: any) => r.caseId === caseId);
};

/**
 * BACKEND INTEGRATION POINT: PUT /api/counsellor/profile
 * Updates counsellor's clinical credentials, bio, and specializations.
 */
export const updateCounsellorProfileApi = async (profileData: any) => {
  await delay(400);
  console.log('[API PUT /api/counsellor/profile]', profileData);
  return { success: true };
};
